name: Validate CrySL Rules

on:
  pull_request:

jobs:
  Validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-package: jdk
          java-version: 11
      - name: Validate Rules with Maven
        run: mvn clean test -f RuleCorrectnessTest